name: Daily PR Update

on:
  workflow_dispatch:
    inputs:
      custom_parameter:
        description: 'A custom parameter'
        required: true
        default: 'default_value'

# on:
#   schedule:
#     - cron: '0 0 * * *'  # 매일 0시에 실행

jobs:
  update-pr-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use the custom parameter
        run: echo Custom Parameter Value ${{ github.event.inputs.custom_parameter }}
      
      - name: Print Secrets
        run: echo ${{ secrets.REPO_OWNER }} ${{ secrets.REPO_NAME }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run Python script
        run: python .github/scripts/clean_comments.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.REPO_OWNER }} ${{ secrets.REPO_NAME }}